package pl.kamilsieczkowski.constants;

public class Texts {
    public static final String LOGIN = "Login";
    public static final String LOGIN_FAILED = "login failed";
    public static final String LOGIN_STATUS = "Login status:";
    public static final String LOGGED_IN = "logged in";
    public static final String PUBLICATIONS = "Publications";
    public static final String ID_NUMBER = "ID number";
    public static final String AUTHOR = "Author";
    public static final String TITLE = "Title";
    public static final String KEY_WORDS = "Key words";
    public static final String SEARCH = "Search";
    public static final String TOME = "Tome";
    public static final String CONDITION = "Condition";
    public static final String EDITION = "Edition";
    public static final String LOCALIZATION = "Placement";
    public static final String BORROW = "Borrow";
    public static final String RETURN = "Return";
    public static final String PROLONG = "Prolong";
    public static final String EDIT_DESCRIPTION = "Edit description";
    public static final String ADD_NEW = "Add new";
    public static final String FOUND = "Found:";
    public static final String AVABILITY = "Avability:";
    public static final String PASSWORD = "Password:";
    public static final String USER = "User:";
    public static final String INSERT = "Insert";
    public static final String END = "End";
    public static final String ISBN = "ISBN/ISSN";
    public static final String YEAR_OF_REALASE = "Year of realase";
    public static final String VALUE = "Value";
    public static final String PUBLISHER = "Publisher";
    public static final String DESCRIPTION = "Description";
    public static final String TOPIC = "Topic";
    public static final String STATE = "State";
    public static final String DATE_OF_AQUISITION = "Date of aquisition";
    public static final String ADD_NEW_BOOK = "Add new book";
    public static final String SPACE = " ";
    public static final String SQL_EXCEPTION ="SQLException";
    public static final String PLACEMENT ="Placement";
    public static final String IN_LIBRARY ="In library";
    public static final String BORROWED ="Borrowed";
    public static final String ALL ="All";
}
